
FROM node:10.14.1-alpine as client

ARG REACT_APP_AUTH0__DOMAIN=NO_VALUE
ARG REACT_APP_AUTH0__CLIENT_ID=NO_VALUE
ARG REACT_APP_AUTH0__REDIRECT_URI=NO_VALUE
ARG REACT_APP_AUTH0__RESPONSE_TYPE=NO_VALUE
ARG REACT_APP_AUTH0__AUDIENCE=NO_VALUE
ARG REACT_APP_AUTH0__SCOPE=NO_VALUE
ARG REACT_APP_AUTH0__ACCESS_TOKEN_USERNAME_KEY=NO_VALUE

ARG REACT_APP_EDITORS__CHIEF=NO_VALUE
ARG REACT_APP_EDITORS__MANAGING=NO_VALUE

ARG REACT_APP_EDITORS__CHIEF=NO_VALUE
ARG REACT_APP_SCOPES__CONCEPT_WRITE=NO_VALUE
ARG REACT_APP_SCOPES__CONCEPT_ADMIN=NO_VALUE
ARG REACT_APP_EXTERNAL_URL__CONCEPT_API=NO_VALUE


ENV REACT_APP_AUTH0__DOMAIN=${REACT_APP_AUTH0__DOMAIN}
ENV REACT_APP_AUTH0__CLIENT_ID=${REACT_APP_AUTH0__CLIENT_ID}
ENV REACT_APP_AUTH0__REDIRECT_URI=${REACT_APP_AUTH0__REDIRECT_URI}
ENV REACT_APP_AUTH0__RESPONSE_TYPE=${REACT_APP_AUTH0__RESPONSE_TYPE}
ENV REACT_APP_AUTH0__AUDIENCE=${REACT_APP_AUTH0__AUDIENCE}
ENV REACT_APP_AUTH0__SCOPE=${REACT_APP_AUTH0__SCOPE}
ENV REACT_APP_AUTH0__ACCESS_TOKEN_USERNAME_KEY=${REACT_APP_AUTH0__ACCESS_TOKEN_USERNAME_KEY}

ENV REACT_APP_EDITORS__CHIEF=${REACT_APP_EDITORS__CHIEF}
ENV REACT_APP_EDITORS__MANAGING=${REACT_APP_AUTH0__ACCESS_TOKEN_USERNAME_KEY}

ENV REACT_APP_EDITORS__CHIEF=${REACT_APP_EDITORS__CHIEF}
ENV REACT_APP_SCOPES__CONCEPT_WRITE=${REACT_APP_SCOPES__CONCEPT_WRITE}
ENV REACT_APP_SCOPES__CONCEPT_ADMIN=${REACT_APP_SCOPES__CONCEPT_ADMIN}
ENV REACT_APP_EXTERNAL_URL__CONCEPT_API=${REACT_APP_EXTERNAL_URL__CONCEPT_API}



WORKDIR /usr/app/client/
COPY client/package*.json ./
RUN npm install -qy
COPY client/ ./
RUN npm run build-css
RUN npm run build

# Setup the server

FROM node:9.4.0-alpine

WORKDIR /usr/app/

WORKDIR /usr/app/server/
COPY --from=client /usr/app/client/build/ ./client/build/
COPY server/package*.json ./
RUN npm install -qy
COPY server/ ./

ENV PORT 80

EXPOSE 80

CMD npm run start-production