version: 0.2

# --------------------------------------------------------------
# Required environment variables
# --------------------------------------------------------------
# REGION -> The AWS region
# REPOSITORY_NAME -> The docker repository name
# REPOSITORY_URI -> The docker repository url
# CONCEPT_API_URL -> The concept api url
# --------------------------------------------------------------

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region $REGION --no-include-email)
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_NAME . --build-arg CONCEPT_API_URL=${CONCEPT_API_URL}
    - docker tag $REPOSITORY_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - echo $REPOSITORY_URI:$IMAGE_TAG
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - printf '[{"name":"%s","imageUri":"%s"}]' $REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imageDefinitions.json
    - echo imageDefinitions.json
artifacts:
  files:
  - imageDefinitions.json

