export const UPDATE_FLASH_MESSAGE_CONCEPT_CLONE = 'UPDATE_FLASH_MESSAGE_CONCEPT_CLONE';
export const UPDATE_INITIAL_FORM_VALUES_FOR_CONCEPT_CLONE = 'UPDATE_INITIAL_FORM_VALUES_FOR_CONCEPT_CLONE';

export const updateInitialFormValues = values => ({type: UPDATE_INITIAL_FORM_VALUES_FOR_CONCEPT_CLONE, payload: values});